### ISSUE TITLE
Telinkrin-shell 2.5.tar.xz misnamed

### ISSUE THREAD

**Issue by LiHRaM** [prasadkumar013/AUR#1]
Using pamac-manager to keep my theme updated, and have been erroring on the shell theme. Turns out it was just a missing hyphen. :)

Should be `Telinkrin-shell-2.5.tar.xz` (note the added hyphen between shell and the pkgversion)

**Comment by wisetux** [comment]
Could you point out exactly where the error is? Cause from what I see, there is already a hyphen 
`.../Telinkrin-shell-$pkgver.tar.xz`

**Comment by LiHRaM** [comment]
Yeah! No problem. The file itself is misnamed in [Sources+Binaries](https://github.com/prasadkumar013/AUR/tree/master/Sources%2BBinaries/Sources/Arrongin_Telinkrin)

![image](https://user-images.githubusercontent.com/25297553/38861649-5d1a7c20-4233-11e8-854b-64b03c96b1dc.png)

You should be able to see that the old version has the hypen, but the new one doesn't.

**Comment by wisetux** [comment]
Thank you. Fixed the file name. Marking issue as closed. Feel free to point out any new issues if they arise.
